package:
  name: imgui_bundle
  version: 1.6.2
  top-level:
    - imgui_bundle

source:
  url: https://github.com/pthom/imgui_bundle/releases/download/v1.6.2/srcs-full-v1.6.2.tar.gz
  sha256: 74d7984f59d9349685dfab4190609af9fab956635522211280cf087f4f2be85f
build:
  # Trigger the build of SDL2 and libhtml5 libraries with -fPIC (aka -sRELOCATABLE=1, within emscripten)
  #   - This module needs to link with SDL2 and html5 in two ways: javascript and native library.
  #     For SDL2, this corresponds to library_sdl.js and $EMSCRIPTEN_SYSROOT/lib/wasm32-emscripten/pic/libSDL2.a (fPIC version)
  #   - The fPIC version is not produced by default by emscripten, so we need to trigger its build below
  #   - Also, at link time, we need to specify the path to the fPIC version of libSDL2.a
  #
  # See https://github.com/pyodide/pyodide/issues/5248 for more explanations.
  script: |
    embuilder build sdl2 libhtml5 --pic
