package:
  name: moderngl
  version: 5.12.0
  top-level:
    - moderngl

source:
  url: https://github.com/moderngl/moderngl/archive/refs/tags/5.12.0.zip
  sha256: 2f206afa7aba3c2cab7fd07821f7a0c372fde4dfce91b2382bf6d997f400fb03
